/**
 * Kronologi bersepadu.
 *
 * `precision`: "day" | "month" | "year" | "range"
 * `track`: lorong naratif untuk paparan timeline berbilang lorong
 * `impact`: "critical" | "high" | "medium" | "context"
 * `links`: id rekod lain (metrik, pelaburan, jadual) untuk drill-down
 */
import { sourceRef } from "./meta.js";

export const timelineTracks = [
  { id: "governance", label: "Tadbir urus & pelantikan", short: "Tadbir urus" },
  { id: "financial", label: "Kewangan & hibah", short: "Kewangan" },
  { id: "audit", label: "Audit & amaran pengawal selia", short: "Audit & amaran" },
  { id: "rescue", label: "Pelan pemulihan & UJSB", short: "Pemulihan" },
  { id: "investment", label: "Pelaburan bermasalah", short: "Pelaburan" },
  { id: "enforcement", label: "Penguatkuasaan & tatatertib", short: "Penguatkuasaan" },
  { id: "hajj", label: "Haji, kos & subsidi", short: "Haji" },
  { id: "inquiry", label: "Suruhanjaya Siasatan Diraja", short: "RCI" },
];

export const timelineEvents = [
  /* ---------- Konteks sejarah ---------- */
  { id: "t-1951", date: "1951", precision: "year", track: "governance", impact: "context", title: "Ordinan Haji 1951", body: "Ordinan Haji 1951 diwujudkan; Pejabat Urusan Hal Ehwal Haji ditubuhkan di Pulau Pinang.", source: [sourceRef("2.1.1", 53, 15)] },
  { id: "t-1962", date: "1962", precision: "year", track: "governance", impact: "context", title: "PWSBH ditubuhkan", body: "Perbadanan Wang Simpanan Bakal-Bakal Haji Tanah Melayu ditubuhkan melalui Akta Parlimen Bil. 34/62.", source: [sourceRef("2.1.2", 53, 15)] },
  { id: "t-1969", date: "1969-08-08", precision: "day", track: "governance", impact: "context", title: "LUTH ditubuhkan", body: "Lembaga Urusan dan Tabung Haji ditubuhkan melalui Akta 8, menggabungkan fungsi PWSBH dengan Pejabat Urusan Hal Ehwal Haji.", source: [sourceRef("2.1.3", 54, 16)] },
  { id: "t-1979", date: "1979", precision: "year", track: "financial", impact: "context", title: "Akad Mudarabah untuk asas zakat", body: "Konsep Mudarabah digunakan bagi menentukan bayaran zakat ke atas deposit pendeposit, berdasarkan keputusan Jawatankuasa Fatwa Majlis Kebangsaan.", links: ["shariah-contract-changes"], source: [sourceRef("3.7.13", 106, 68)] },
  { id: "t-1995", date: "1995-06-01", precision: "day", track: "governance", impact: "high", title: "LTH menggantikan LUTH", body: "LUTH dimansuhkan; Lembaga Tabung Haji diwujudkan melalui Akta Tabung Haji 1995 (Akta 535), yang berkuat kuasa 16 Februari 1995.", source: [sourceRef("2.1.4 / 3.2.8", 54, 16)] },
  { id: "t-2001", date: "2001", precision: "year", track: "hajj", impact: "high", title: "HAFIS bermula", body: "Pemberian Bantuan Kewangan Haji (HAFIS) bermula. Sebelum ini jemaah haji Muassasah perlu membayar kos haji sebenar.", links: ["hafis-actual"], source: [sourceRef("Ringkasan Eksekutif ¶22(v)", 23, "xxi")] },
  { id: "t-2009-freeze", date: "2009", precision: "year", track: "hajj", impact: "critical", title: "Bayaran haji dibekukan pada RM9,980", body: "Kerajaan membekukan kenaikan bayaran haji Muassasah. Bayaran kekal RM9,980 sehingga 2021 — tiga belas tahun — walaupun kos haji terus meningkat.", links: ["hafis-actual"], source: [sourceRef("3.17.4 / 3.16.5", 211, 173)] },
  { id: "t-2010-classification", date: "2010", precision: "year", track: "audit", impact: "critical", title: "Kumpulan Wang Pendeposit dikelaskan sebagai ekuiti", body: "Sejak 2010 JAN menerima penyata kewangan LTH yang mengelaskan Kumpulan Wang Pendeposit sebagai dana (ekuiti), bukan liabiliti. Suruhanjaya menyifatkan ini sebagai representasi salah.", links: ["depositor-fund-classification"], source: [sourceRef("3.11.12", 132, 94)] },

  /* ---------- 2011–2013: benih pelaburan bermasalah ---------- */
  { id: "t-2009-trurich", date: "2009-11-30", precision: "day", track: "investment", impact: "medium", title: "Trurich Resources ditubuhkan", body: "Usaha sama dengan Felda Global Ventures Kalimantan untuk membangun sehingga 200,000 hektar tanah perladangan di Kalimantan.", links: ["trurich"], source: [sourceRef("3.14.6(5)", 181, 143)] },
  { id: "t-2009-abraj", date: "2009-11-11", precision: "day", track: "investment", impact: "medium", title: "Usaha sama Abraj dengan Amanah Raya Berhad", body: "Pelaburan usaha sama dalam pembelian hartanah.", links: ["abraj"], source: [sourceRef("3.14.6(6)", 182, 144)] },
  { id: "t-2012-fgv", date: "2012-05-09", precision: "day", track: "investment", impact: "high", title: "Kelulusan pelaburan IPO FGV", body: "LTH mendapat kelulusan melanggan sehingga 276 juta unit saham FGV pada harga IPO RM4.65/unit (7.5% pegangan).", links: ["fgv"], source: [sourceRef("3.14.6(14)", 192, 154)] },
  { id: "t-2012-thip-sale", date: "2012", precision: "year", track: "investment", impact: "critical", title: "Penjualan 95% saham THIP", body: "LTH menjual pegangan 95% dalam PT TH Indo Plantations kepada PT Borneo Pacific, dianggarkan USD910 juta. Kemudian menjadi subjek laporan polis dan siasatan forensik.", links: ["thip"], source: [sourceRef("3.15.3", 194, 156)] },
  { id: "t-2012-thp-sukuk", date: "2012", precision: "range", dateEnd: "2014", track: "investment", impact: "high", title: "THP membiayai pembelian ladang dengan Sukuk RM1.2 bilion", body: "TH Plantations membiayai pembelian ladang baharu 2012–2014, terutamanya dengan Sukuk RM1.2 bilion yang dikeluarkan LTH. Hanya 58% ladang THP produktif.", links: ["thp"], source: [sourceRef("3.14.6(10)", 188, 150)] },
  { id: "t-2013-chair", date: "2013-07-01", precision: "day", track: "governance", impact: "high", title: "Datuk Seri Abdul Azeez dilantik Pengerusi LTH", body: "Ahli Parlimen Baling dan Ahli Majlis Tertinggi UMNO dilantik sebagai Pengerusi, memegang jawatan sehingga Mei 2018.", source: [sourceRef("2.2.15", 59, 21)] },
  { id: "t-2013-alfareeda", date: "2013-02-21", precision: "day", track: "investment", impact: "medium", title: "Pelaburan Al-Fareeda Residential Fund", body: "LTH melanggan sehingga SR76 juta (RM63 juta) — 13.8% daripada dana SR550 juta. Kemudian dihapus kira sepenuhnya.", links: ["al-fareeda"], source: [sourceRef("3.14.6(9)", 188, 150)] },

  /* ---------- 2014: permulaan tempoh siasatan ---------- */
  { id: "t-2014-start", date: "2014", precision: "year", track: "financial", impact: "critical", title: "Tempoh siasatan bermula — jurang defisit muncul", body: "Analisis PwC menunjukkan lebihan sebelum agihan RM2,885 juta, tetapi agihan hibah RM3,237 juta menghasilkan kekurangan RM352 juta selepas agihan. Ini tahun pertama jurang defisit.", links: ["assets-liabilities", "hibah-amounts"], source: [sourceRef("3.13.7", 147, 109)] },
  { id: "t-2014-bnm-1", date: "2014-08-21", precision: "day", track: "audit", impact: "high", title: "Amaran bertulis BNM yang pertama", body: "Surat BNM kepada Pengerusi LTH: 'Deposit Taking and Management of Liquidity'.", links: ["bnm-warnings-ignored"], source: [sourceRef("3.6.2", 100, 62)] },
  { id: "t-2014-bnm-2", date: "2014-12-19", precision: "day", track: "audit", impact: "medium", title: "Amaran BNM: pengambilan deposit dan pengurusan kecairan", body: "Surat kedua BNM kepada Pengerusi LTH.", source: [sourceRef("3.6.2 / 3.17.10", 100, 62)] },
  { id: "t-2014-bonus", date: "2014", precision: "year", track: "governance", impact: "high", title: "Peruntukan bonus tertinggi: RM74 juta", body: "Bonus luar biasa pada kadar 1–11 bulan gaji tahunan tambah 2 bulan bonus khas — sehingga 13 bulan gaji — melibatkan peruntukan RM74 juta (2.5% keuntungan bersih).", links: ["staff-bonus", "bonus-vs-profit"], source: [sourceRef("3.12.9", 138, 100)] },
  { id: "t-2014-wellspring", date: "2014-09-21", precision: "day", track: "investment", impact: "medium", title: "Pelaburan Wellspring Worldwide", body: "LTH membeli 10% ekuiti berjumlah RM18.4 juta.", links: ["wellspring"], source: [sourceRef("3.14.6(3)", 179, 141)] },
  { id: "t-2014-dssb", date: "2014-10-21", precision: "day", track: "investment", impact: "high", title: "Kelulusan pelaburan Deru Semangat (peringkat pertama)", body: "Menteri Hal Ehwal Agama meluluskan pelaburan sehingga RM526.16 juta untuk usahasama ladang kelapa sawit di Mukim Tembeling, Pahang. Kelulusan kedua 19 Januari 2015.", links: ["dssb"], source: [sourceRef("3.14.6(4)", 180, 142)] },
  { id: "t-2014-ppb", date: "2014-12", precision: "month", track: "investment", impact: "high", title: "Pembelian 30% Putrajaya Perdana Berhad", body: "LTH membeli 30% ekuiti berjumlah RM193.50 juta daripada Cendana Destini Sdn. Bhd., dengan objektif penyenaraian dalam tempoh satu tahun.", links: ["ppb"], source: [sourceRef("3.14.6(7)", 183, 145)] },

  /* ---------- 2015 ---------- */
  { id: "t-2015-deficit", date: "2015", precision: "year", track: "financial", impact: "critical", title: "Kekurangan selepas agihan melonjak kepada RM3,086 juta", body: "Lebihan sebelum agihan hanya RM134 juta, tetapi agihan hibah RM3,220 juta (5.00% + 3.00%).", links: ["assets-liabilities"], source: [sourceRef("3.13.7", 147, 109)] },
  { id: "t-2015-jps", date: "2015", precision: "year", track: "governance", impact: "medium", title: "Jawatankuasa Penasihat Syariah ditubuhkan", body: "JPS ditubuhkan di bawah seksyen 11 Akta 535. Pelaburan oleh Jawatankuasa Kewangan dan Pelaburan LTH tiada dalam skop keputusan JPS sehingga 2016.", source: [sourceRef("3.5.16 / 3.5.20", 94, 56)] },
  { id: "t-2015-alrawda-1", date: "2015-04-03", precision: "day", track: "investment", impact: "high", title: "Perjanjian pajakan Al-Rawda yang pertama", body: "Perjanjian pajakan/sub-pajakan jangka panjang bagi hotel di Makkah dan Madinah. Dua lagi perjanjian menyusul pada 2016 dan 2017.", links: ["al-rawda"], source: [sourceRef("3.14.6(8)", 184, 146)] },
  { id: "t-2015-marine", date: "2015-06-18", precision: "day", track: "investment", impact: "high", title: "Kelulusan pelaburan TH Marine", body: "Menteri Hal Ehwal Agama meluluskan pelaburan 51% ekuiti dalam usaha sama dengan Alam Maritim Resources Berhad.", links: ["th-marine"], source: [sourceRef("3.14.6(12)", 190, 152)] },
  { id: "t-2015-bnm-3", date: "2015-12-23", precision: "day", track: "audit", impact: "high", title: "BNM menulis kepada Pengerusi LTH DAN Menteri", body: "Dua surat pada tarikh sama: 'Keperluan Merumus Dasar Rizab' kepada Pengerusi, dan 'Pengurusan Kewangan Lembaga Tabung Haji' kepada Menteri. Surat ini turut membangkitkan kemampuan LTH membayar hibah yang tinggi.", links: ["bnm-warnings-ignored"], source: [sourceRef("3.6.2 / 3.11.6", 100, 62)] },

  /* ---------- 2016 ---------- */
  { id: "t-2016-deficit", date: "2016", precision: "year", track: "financial", impact: "critical", title: "Aset jatuh di bawah liabiliti buat kali pertama", body: "Kekurangan SEBELUM agihan sebanyak RM1,260 juta — bermakna syarat seksyen 22(3)(a) tidak dipenuhi sebelum sebarang hibah diisytiharkan. Hibah RM2,871 juta tetap dibayar.", links: ["assets-liabilities", "s22-3a"], source: [sourceRef("3.13.7 / 3.11.2", 147, 109)] },
  { id: "t-2016-akad", date: "2016", precision: "year", track: "financial", impact: "high", title: "Akad ditukar kepada Wadi'ah Yad Dhamanah", body: "Akad deposit ditukar daripada Mudarabah kepada Wadi'ah Yad Dhamanah. Suruhanjaya mendapati tiada penjelasan mengapa, dan tiada kajian menyeluruh dilaksanakan sebelum perubahan.", links: ["shariah-contract-changes"], source: [sourceRef("3.7.16 / 3.7.21", 107, 69)] },
  { id: "t-2016-ey-rav", date: "2016-06-30", precision: "day", track: "audit", impact: "critical", title: "EY mengeluarkan laporan rangka kerja RAV", body: "EY mengesyorkan metodologi menilai aset LTH; merujuk seksyen 22(3)(a) yang tiada definisi atau garis panduan jelas. Metodologi ini digunakan untuk pelaporan 2015, 2016 dan 2017.", links: ["rav-2017", "ey-rav-role"], source: [sourceRef("3.11.5", 127, 89)] },
  { id: "t-2016-ey-proforma", date: "2016-09-30", precision: "day", track: "audit", impact: "high", title: "Laporan Proforma EY bagi FY2015", body: "EY mengeluarkan laporan ke atas Laporan Proforma kedudukan kewangan LTH bagi tahun berakhir 31 Disember 2015, menunjukkan kedudukan aset melebihi liabiliti.", links: ["ey-rav-role"], source: [sourceRef("3.11.5", 127, 89)] },
  { id: "t-2016-annual-report", date: "2016-10-19", precision: "day", track: "governance", impact: "medium", title: "Laporan Tahunan TH 2015 dibentangkan ke Dewan Rakyat", body: "Istilah 'Nilai Aset Terlaras (Net Worth Adjusted)' diperkenalkan di muka surat 127 Laporan Tahunan 2015.", links: ["cfo-position"], source: [sourceRef("3.11.5", 128, 90)] },
  { id: "t-2016-emrail", date: "2016-06-07", precision: "day", track: "investment", impact: "medium", title: "Pembelian 15.3% ekuiti Emrail", body: "RM20.17 juta daripada Lingkaran Hartaniaga Sdn. Bhd., dengan Hak Opsyen Jual dalam perjanjian bertarikh 20 Mei 2016.", links: ["emrail"], source: [sourceRef("3.14.6(2)", 178, 140)] },
  { id: "t-2016-bnm-4", date: "2016-12-14", precision: "day", track: "audit", impact: "medium", title: "Amaran BNM: keperluan merumus dasar rizab", body: "Surat BNM kepada LTH. Suruhanjaya mendapati surat-surat ini tidak mendapat perhatian yang sewajarnya.", links: ["bnm-warnings-ignored"], source: [sourceRef("3.17.10", 212, 174)] },

  /* ---------- 2017: tahun kritikal ---------- */
  { id: "t-2017-bnm-5", date: "2017-02-17", precision: "day", track: "audit", impact: "medium", title: "Amaran BNM terakhir sebelum krisis", body: "Surat BNM mengenai keperluan merumus dasar rizab.", links: ["bnm-warnings-ignored"], source: [sourceRef("3.17.10", 212, 174)] },
  { id: "t-2017-rb-1", date: "2017-03-03", precision: "day", track: "audit", impact: "high", title: "Laporan Roland Berger: 5-Year Strategic Business Plan Review", body: "RB dilantik sebagai perunding pada 2017. Laporan mendapati LTH menghadapi masalah termasuk ketidaksesuaian model pengurusan dan perniagaan yang berisiko, serta subsidi haji yang tinggi. RB juga menganggarkan kerugian RM2.6 bilion akan menjadi ancaman kepada pendapatan masa hadapan.", links: ["reserve-policy"], source: [sourceRef("3.9.15 / 3.17.11 / Jilid 11", 117, 79)] },
  { id: "t-2017-crisis", date: "2017", precision: "year", track: "financial", impact: "critical", title: "Krisis kewangan: keuntungan RM3.4 bilion sepatutnya kerugian RM1.4 bilion", body: "Jika piawaian MFRS digunakan sepenuhnya, LTH sepatutnya merekodkan kerugian bersih RM1.4 bilion dan kerugian terkumpul RM4.7 bilion setakat 31 Disember 2017.", links: ["pwc-adjustment-2017", "impairment-policy-2017"], source: [sourceRef("3.13.11", 149, 111)] },
  { id: "t-2017-impairment", date: "2017", precision: "year", track: "audit", impact: "critical", title: "Polisi rosot nilai diubah dua kali dalam satu tahun", body: "Ambang rosot nilai dinaikkan daripada 70% kepada 85% kemudian 90% di bawah kos — membolehkan LTH merekodkan rosot nilai sebanyak RM1.0 juta sahaja pada 2017.", links: ["impairment-policy-2017"], source: [sourceRef("3.13.8–3.13.9", 147, 109)] },
  { id: "t-2017-annual-report", date: "2017-08-02", precision: "day", track: "governance", impact: "medium", title: "Laporan Tahunan TH 2016 dibentangkan ke Dewan Rakyat", body: "Istilah Nilai Aset Terlaras digunakan sekali lagi di muka surat 102.", links: ["cfo-position"], source: [sourceRef("3.11.5", 128, 90)] },
  { id: "t-2017-emrail-put", date: "2017-04-26", precision: "day", track: "investment", impact: "medium", title: "Notis Put Option Emrail", body: "Selepas IPO Emrail dibatalkan dan sasaran keuntungan RM36.1 juta gagal dicapai. LHSB hanya membayar RM2 juta daripada RM20.3 juta.", links: ["emrail"], source: [sourceRef("3.14.6(2)", 178, 140)] },
  { id: "t-2017-thp-bonus", date: "2017-04-12", precision: "day", track: "governance", impact: "high", title: "Exco TH Properties meluluskan bonus istimewa RM1.15 juta", body: "Kelulusan kemudian didapati tidak mematuhi resolusi Lembaga TH Properties dan seksyen 230(2) dan 230(4) Akta Syarikat 2016.", links: ["thp-bonus-2017", "thp-bonus-legal"], source: [sourceRef("3.12.20", 141, 103)] },

  /* ---------- 2018: peralihan ---------- */
  { id: "t-2018-hibah-method", date: "2018-02-07", precision: "day", track: "financial", impact: "high", title: "Pertukaran kaedah pengiraan hibah diumumkan lalu ditarik balik", body: "Pertukaran daripada purata baki bulanan kepada purata baki tahunan diumumkan, kemudian ditarik balik selepas reaksi negatif pendeposit. Kaedah bulanan digunakan semula, menyebabkan LTH mengeluarkan lebihan wang RM600 juta.", links: ["hibah-calc-change-2017"], source: [sourceRef("3.9.9", 115, 77)] },
  { id: "t-2018-board-meetings", date: "2018-02-06", precision: "day", dateEnd: "2018-02-09", track: "financial", impact: "critical", title: "Dua Mesyuarat Khas Lembaga mengenai hibah 2017", body: "Dua kertas kerja dibentangkan kepada Mesyuarat Khas Lembaga Pengarah pada 6 dan 9 Februari 2018. Laporan polis kemudiannya mendakwa wujud salah nyataan dalam kertas kerja ini bagi membolehkan hibah tinggi diisytiharkan.", links: ["pr-hibah-2017"], source: [sourceRef("3.15.8", 196, 158)] },
  { id: "t-2018-minutes", date: "2018-02-14", precision: "day", track: "financial", impact: "high", title: "Pembentangan semula laporan kewangan dengan pindaan polisi rosot nilai", body: "Minit mesyuarat KKTH1/MK3-18(Bil1): pembentangan semula laporan kewangan belum disatukan (belum diaudit) berserta pindaan semula polisi rosot nilai dan hibah pendeposit bagi tahun berakhir 31 Disember 2017.", links: ["cfo-position"], source: [sourceRef("3.11.5", 129, 91)] },
  { id: "t-2018-rb-2", date: "2018-02-02", precision: "day", track: "audit", impact: "high", title: "Laporan akhir Roland Berger (versi disemak)", body: "Laporan RB disiapkan dan diberikan kepada pengurusan LTH SEBELUM agihan hibah 2017 diisytiharkan. Tiada rekod menunjukkan ia dibentangkan kepada Lembaga.", links: ["political-influence"], source: [sourceRef("3.17.13 / Jilid 11", 213, 175)] },
  { id: "t-2018-thp-aus-bonus", date: "2018-04-23", precision: "day", track: "governance", impact: "medium", title: "Lembaga THP Australia meluluskan bonus RM1.045 juta", body: "Diratifikasi di Mesyuarat Agong tujuh bulan kemudian (30 November 2018) — tidak mematuhi seksyen 230(3) Akta 777.", links: ["thp-australia-bonus-2018"], source: [sourceRef("3.12.23–3.12.24", 142, 104)] },
  { id: "t-2018-ppb-put", date: "2018-03-07", precision: "day", track: "investment", impact: "medium", title: "Notis Put Option Putrajaya Perdana Berhad", body: "LTH menuntut CDSB mengambil alih saham PPB pada harga RM210.7 juta. CDSB gagal membuat bayaran.", links: ["ppb"], source: [sourceRef("3.14.6(7)", 183, 145)] },
  { id: "t-2018-panel-dissolved", date: "2018-05", precision: "month", track: "governance", impact: "critical", title: "Panel Pelaburan dibubarkan", body: "Digantikan Exco Perniagaan yang dipengerusikan Menteri Hal Ehwal Ekonomi. Saksi mengakui Exco Perniagaan tidak pernah berfungsi.", links: ["investment-panel"], source: [sourceRef("3.5.7–3.5.8", 92, 54)] },
  { id: "t-2018-chair-out", date: "2018-05-23", precision: "day", track: "governance", impact: "high", title: "Pengerusi Datuk Seri Abdul Azeez tamat perkhidmatan", body: "Bersama beberapa anggota Lembaga lain yang tamat perkhidmatan sepanjang 2018.", source: [sourceRef("2.2.15", 59, 21)] },
  { id: "t-2018-pm-power", date: "2018-05-10", precision: "day", dateEnd: "2018-07-01", track: "governance", impact: "medium", title: "Kuasa Menteri dijalankan oleh Perdana Menteri", body: "Melalui P.U.(A) 125, Tun Dr. Mahathir bin Mohamad dipertanggungjawabkan sehingga pelantikan Menteri baharu.", source: [sourceRef("2.2.7", 56, 18)] },
  { id: "t-2018-ey-rav-report", date: "2018-05-23", precision: "day", track: "audit", impact: "critical", title: "EY mengeluarkan Laporan Semakan RAV bagi FY2017", body: "Dikeluarkan 54 hari SEBELUM Penyata Kewangan Beraudit JAN dimuktamadkan (16 Julai 2018) — bercanggah dengan dakwaan bahawa Proforma berasaskan penyata beraudit.", links: ["ey-rav-role"], source: [sourceRef("3.9.19", 118, 80)] },
  { id: "t-2018-kan-pm-meeting", date: "2018-07-04", precision: "day", track: "audit", impact: "critical", title: "Perbincangan KAN dengan Perdana Menteri", body: "KAN memaklumkan bahawa Pendapat Berteguran dicadangkan sekiranya tiada pelarasan dibuat untuk dua penemuan material.", links: ["audit-failure"], source: [sourceRef("3.11.15", 133, 95)] },
  { id: "t-2018-clean-cert", date: "2018-07-16", precision: "day", track: "audit", impact: "critical", title: "Sijil Audit Bersih dengan 'Emphasis of Matter' dikeluarkan", body: "KAN memberi Pendapat Tanpa Teguran dengan 'Emphasis of Matter' selepas mempertimbangkan kesan persepsi pihak berkepentingan. Suruhanjaya menyifatkan ini sebagai pertimbangan di luar skop audit.", links: ["audit-failure"], source: [sourceRef("3.11.15 / 3.13.5", 133, 95)] },
  { id: "t-2018-new-mgmt", date: "2018-07-10", precision: "day", track: "governance", impact: "high", title: "Barisan pengurusan baharu: Tan Sri Md Nor (Pengerusi) dan Dato' Sri Zukri (KPE)", body: "Lembaga dan pengurusan yang dilantik antara Julai dan Ogos 2018 melantik PwC untuk melaksanakan Financial Review.", source: [sourceRef("2.2.15 / 2.2.24 / 3.13.6", 59, 21)] },
  { id: "t-2018-thp-ceo", date: "2018-08-20", precision: "day", track: "investment", impact: "medium", title: "KPE TH Plantations meletakkan jawatan", body: "Selepas diletakkan dalam cuti (garden leave) berikutan isu tadbir urus THP.", links: ["thp"], source: [sourceRef("3.14.6(10)", 189, 151)] },
  { id: "t-2018-ey-subsidiaries", date: "2018-10-26", precision: "day", track: "audit", impact: "medium", title: "Laporan EY: Business Review of TH's Investee Companies", body: "Bersama Laporan Penilaian Anak Syarikat bertarikh 28 Oktober 2018 yang mengesyorkan aset pelaburan strategik berprestasi rendah.", links: ["strategic-investment-assessment"], source: [sourceRef("3.13.24 / Jilid 9", 157, 119)] },
  { id: "t-2018-kan-letter", date: "2018-10-25", precision: "day", track: "audit", impact: "high", title: "Surat KAN kepada Pengerusi LTH", body: "Ulasan JAN mengenai pandangan Lembaga Pengarah terhadap Penyata Kewangan LTH bagi tahun berakhir 31 Disember 2017.", source: [sourceRef("3.9.14 / Jilid 12", 117, 79)] },
  { id: "t-2018-police-1", date: "2018-11-30", precision: "day", track: "enforcement", impact: "high", title: "Dua laporan polis dibuat", body: "Dang Wangi/31347/2018 (Yayasan Tabung Haji) dan Dang Wangi/31331/2018 (penjualan saham THIP).", links: ["pr-yth", "pr-thip"], source: [sourceRef("3.15.1–3.15.3", 193, 155)] },
  { id: "t-2018-pwc-final", date: "2018-11-09", precision: "day", track: "audit", impact: "critical", title: "Laporan akhir PwC: Financial Position Review", body: "PwC mendapati jurang defisit antara nilai aset dan liabiliti LTH sejak 2014, dan hibah yang diagihkan sejak 2014 bercanggah dengan seksyen 22 Akta 535.", links: ["assets-liabilities", "pwc-adjustment-2017"], source: [sourceRef("3.13.6–3.13.7 / Jilid 11", 147, 109)] },
  { id: "t-2018-cabinet-30nov", date: "2018-11-30", precision: "day", track: "rescue", impact: "high", title: "Jemaah Menteri bersetuju secara dasar", body: "Bersetuju terhadap rangka kerja Pelan Pemulihan dan Penstrukturan LTH; LTH diminta berbincang dengan MOF bagi perincian pelaksanaan.", links: ["ujsb"], source: [sourceRef("3.13.21", 156, 118)] },
  { id: "t-2018-cabinet-7dec", date: "2018-12-07", precision: "day", track: "rescue", impact: "critical", title: "Jemaah Menteri meluluskan Pelan Pemulihan — laksana sebelum akhir tahun", body: "Juga memutuskan meletakkan LTH secara pentadbiran di bawah kawal selia BNM mulai 1 Januari 2019, tanpa menyatakan skop kawal selia dengan jelas. LTH mempunyai kurang dari dua minggu untuk memuktamadkan pelan.", links: ["ujsb", "bnm-oversight"], source: [sourceRef("3.13.22 / 3.6.3", 156, 118)] },
  { id: "t-2018-police-3", date: "2018-12-13", precision: "day", track: "enforcement", impact: "medium", title: "Laporan polis ketiga: Trurich", body: "Dang Wangi/32724/2018 oleh mantan Setiausaha Trurich mengenai perjanjian pembelian saham di Indonesia.", links: ["pr-trurich"], source: [sourceRef("3.15.5", 195, 157)] },
  { id: "t-2018-ujsb", date: "2018-12-14", precision: "day", track: "rescue", impact: "critical", title: "UJSB ditubuhkan", body: "Urusharta Jamaah Sdn. Bhd. ditubuhkan sebagai syarikat pegangan pelaburan dan pengurusan aset milik penuh Menteri Kewangan Diperbadankan.", links: ["ujsb"], source: [sourceRef("3.13.2", 145, 107)] },
  { id: "t-2018-pm-approval", date: "2018-12-19", precision: "day", track: "rescue", impact: "high", title: "Perdana Menteri meluluskan pemindahan aset kepada SPV", body: "Kelulusan memindahkan aset berprestasi rendah kepada UJSB.", links: ["ujsb"], source: [sourceRef("3.13.1", 145, 107)] },
  { id: "t-2018-kan-pm-letter", date: "2018-12-19", precision: "day", track: "audit", impact: "critical", title: "Surat KAN kepada Perdana Menteri menjelaskan keputusan audit 2017", body: "Mengesahkan Pendapat Berteguran dicadangkan tetapi Pendapat Tanpa Teguran dengan 'Emphasis of Matter' diberikan setelah mengambil kira persepsi pendeposit.", links: ["audit-failure"], source: [sourceRef("3.11.15", 133, 95)] },
  { id: "t-2018-ata", date: "2018-12-27", precision: "day", track: "rescue", impact: "critical", title: "Perjanjian Pemindahan Aset ditandatangani", body: "Pemindahan 106 saham tersenarai, sebuah syarikat perladangan dan 29 aset hartanah pada nilai RM19.9 bilion (berbanding nilai pasaran RM9.7 bilion).", links: ["asset-transfer"], source: [sourceRef("3.13.23 / 3.13.28", 156, 118)] },
  { id: "t-2018-bnm-pm", date: "2018-12-28", precision: "day", track: "audit", impact: "high", title: "Surat BNM kepada Perdana Menteri", body: "Pengawalseliaan dan cadangan langkah-langkah kehematan ke atas LTH.", source: [sourceRef("3.6.5 / Jilid 12", 101, 63)] },

  /* ---------- 2019 ---------- */
  { id: "t-2019-police-4", date: "2019-01-16", precision: "day", track: "enforcement", impact: "high", title: "Laporan polis keempat: pengisytiharan hibah 2017", body: "Dang Wangi/1484/2019 mendakwa pengisytiharan hibah 2017 bercanggah dengan seksyen 22 Akta 535 dan wujud salah nyataan dalam kertas kerja Lembaga.", links: ["pr-hibah-2017"], source: [sourceRef("3.15.8", 196, 158)] },
  { id: "t-2019-bnm-exam", date: "2019-01-17", precision: "day", dateEnd: "2019-02-28", track: "audit", impact: "high", title: "Pemeriksaan BNM ke atas LTH", body: "Dilaksanakan di bawah seksyen 33 Akta BNM 2009 dan seksyen 25 Akta Pencegahan Pengubahan Wang Haram.", links: ["bnm-oversight"], source: [sourceRef("3.6.5", 101, 63)] },
  { id: "t-2019-hibah-125", date: "2019", precision: "year", track: "financial", impact: "critical", title: "Hibah 2018 diisytiharkan pada 1.25% — deposit mengecut", body: "Saiz deposit LTH menurun daripada kira-kira RM73 bilion sebelum pengumuman kepada RM69 bilion pada akhir 2019 (−RM4 bilion). Pengecutan tertumpu dalam kalangan pendeposit besar.", links: ["deposit-trajectory", "hibah-rates"], source: [sourceRef("3.9.29", 122, 84)] },
  { id: "t-2019-cabinet-funding", date: "2019-04-05", precision: "day", track: "rescue", impact: "critical", title: "Jemaah Menteri meluluskan peruntukan sekurang-kurangnya RM17.8 bilion", body: "RM500 juta pada 2020 di bawah RMK-11, dan sekurang-kurangnya RM17.3 bilion (purata RM1.73 bilion setahun) di bawah RMK-12 dan RMK-13.", links: ["government-funding"], source: [sourceRef("3.13.46", 165, 127)] },
  { id: "t-2019-thp-forensic", date: "2019-04-25", precision: "day", track: "investment", impact: "high", title: "Laporan forensik PwC ke atas TH Plantations", body: "Mendapati pengurusan kanan THP dan Lembaga gagal memenuhi tanggungjawab fidusiari. Laporan dibuat kepada PDRM, SPRM dan Suruhanjaya Sekuriti Malaysia.", links: ["thp"], source: [sourceRef("3.14.6(10)", 188, 150)] },
  { id: "t-2019-sukuk", date: "2019-05-15", precision: "day", track: "rescue", impact: "critical", title: "Perjanjian Langganan Sukuk dan Hak Penolakan Pertama dimeterai", body: "Sukuk Siri 1 RM10 bilion (nominal RM13.2 bilion, 7 tahun, 4.05%) dan Siri 2 RM9.6 bilion (nominal RM14.3 bilion, 10 tahun, 4.10%).", links: ["ujsb-sukuk"], source: [sourceRef("3.13.23 / 3.13.41", 156, 118)] },
  { id: "t-2019-comfort", date: "2019-05-27", precision: "day", track: "rescue", impact: "high", title: "Surat Sokongan Kewangan Menteri Kewangan (bukan jaminan)", body: "Suruhanjaya berpendapat surat tersebut hanyalah 'Letter of Comfort'. Sukuk UJSB TIDAK dijamin oleh Kerajaan, tetapi dimasukkan dalam senarai Komitmen Jaminan.", links: ["ujsb-sukuk", "guarantee-commitments"], source: [sourceRef("3.13.45", 164, 126)] },
  { id: "t-2019-bnm-zakat", date: "2019-06-26", precision: "day", track: "audit", impact: "medium", title: "BNM membangkitkan isu zakat di bawah akad Wadi'ah", body: "Surat kepada Perdana Menteri: penzahiran berkenaan zakat kepada pendeposit mungkin tidak sama dengan kontrak di bawah Wadi'ah Yad Dhamanah.", links: ["shariah-contract-changes"], source: [sourceRef("3.7.18", 108, 70)] },
  { id: "t-2019-reserve", date: "2019", precision: "year", track: "financial", impact: "high", title: "Polisi rizab diperkukuh", body: "RPK ditetapkan pada 5% nilai aset bersih atau RM3.5 bilion; pemindahan tahunan 0.1% ke Rizab Berkanun; 2% keuntungan selepas zakat ke akaun RPK.", links: ["reserve-policy"], source: [sourceRef("3.7.9", 105, 67)] },
  { id: "t-2019-wakalah", date: "2019-12", precision: "month", track: "financial", impact: "high", title: "Akad ditukar kepada Wakalah", body: "Selepas kajian menyeluruh, LTH menjadi ejen pendeposit. Menyelesaikan isu tanggungan zakat pendeposit dan pemberian subsidi.", links: ["shariah-contract-changes"], source: [sourceRef("3.7.22", 109, 71)] },
  { id: "t-2019-rofr-release", date: "2019-12-03", precision: "day", track: "rescue", impact: "medium", title: "LTH melepaskan Hak Penolakan Pertama bagi 18 hartanah", body: "Daripada 19 hartanah yang dicadangkan UJSB pada 19 November 2019; kecuali sebidang tanah di Jalan Hill, Seremban yang kemudiannya juga dilepaskan.", links: ["ujsb-disposals"], source: [sourceRef("3.13.53", 168, 130)] },
  { id: "t-2019-cash-1", date: "2019-12-30", precision: "day", track: "rescue", impact: "medium", title: "Bayaran tunai pertama UJSB kepada LTH: RM100 juta", body: "Sebahagian daripada RM300 juta bagi pengambilan saham tidak patuh syariah.", links: ["ujsb-sukuk"], source: [sourceRef("3.13.42", 163, 125)] },

  /* ---------- 2020–2021 ---------- */
  { id: "t-2020-grant", date: "2020", precision: "year", track: "rescue", impact: "high", title: "UJSB menerima geran Kerajaan RM500 juta", body: "RM300 juta untuk bayaran saham berubah taraf patuh syariah dan RM200 juta untuk menebus Sukuk UJSB kepada LTH.", links: ["government-funding"], source: [sourceRef("3.13.47", 166, 128)] },
  { id: "t-2020-no-hajj", date: "2020", precision: "range", dateEnd: "2021", track: "hajj", impact: "high", title: "Tiada penghantaran jemaah haji", body: "Operasi haji terganggu akibat pandemik Covid-19 pada 2020 dan 2021.", links: ["hafis-actual"], source: [sourceRef("3.16.3 / 3.16.20", 203, 165)] },
  { id: "t-2020-property-sale", date: "2020", precision: "year", track: "rescue", impact: "medium", title: "Hanya satu hartanah UJSB berjaya dijual", body: "Tanah di Mukim Sungai Segamat, Johor, RM920 ribu melalui tender terbuka. Baki 17 hartanah tidak mendapat bidaan.", links: ["ujsb-disposals"], source: [sourceRef("3.13.51 / 3.13.54", 167, 129)] },
  { id: "t-2020-thp-audit", date: "2020-02-05", precision: "day", track: "enforcement", impact: "medium", title: "Laporan Audit Dalam TH Properties mengenai bonus istimewa", body: "'Payment of Special Appreciation Bonus to Certain Directors & Seven Staff Members'. Tetuan Tajuddin & Co dilantik melaksanakan siasatan.", links: ["thp-bonus-legal"], source: [sourceRef("3.14.6(11)", 189, 151)] },
  { id: "t-2020-recovery", date: "2020-08-12", precision: "day", track: "enforcement", impact: "medium", title: "Lembaga TH Properties memutuskan mendapatkan semula bonus", body: "Keputusan mendapatkan kembali bonus yang diberikan kepada Ahli Lembaga Pengarah bagi 2017–2018.", links: ["thp-bonus-legal"], source: [sourceRef("3.14.6(11)", 190, 152)] },
  { id: "t-2020-early-redemption", date: "2020-11-30", precision: "day", track: "rescue", impact: "medium", title: "Penebusan awal Sukuk RM200 juta", body: "Penebusan awal pertama dan setakat ini satu-satunya.", links: ["government-funding"], source: [sourceRef("3.13.47", 166, 128)] },
  { id: "t-2020-abraj-exit", date: "2020-12", precision: "month", track: "investment", impact: "medium", title: "Amanah Raya Berhad membeli 50% pegangan LTH dalam Abraj", body: "LTH mengalami kerugian rosot nilai RM40.25 juta daripada jumlah pegangan ekuiti RM85 juta.", links: ["abraj"], source: [sourceRef("3.14.6(6)", 183, 145)] },
  { id: "t-2020-cash-2", date: "2020-12-30", precision: "day", track: "rescue", impact: "medium", title: "Bayaran tunai kedua UJSB kepada LTH: RM200 juta", body: "Melengkapkan RM300 juta bagi pengambilan saham tidak patuh syariah.", links: ["ujsb-sukuk"], source: [sourceRef("3.13.42", 163, 125)] },
  { id: "t-2020-trurich-disposal", date: "2020-12-22", precision: "day", track: "investment", impact: "medium", title: "Kelulusan pelupusan anak syarikat Trurich", body: "Menteri Hal Ehwal Agama meluluskan; urusan pelupusan diserahkan kepada FGV dan Maybank.", links: ["trurich"], source: [sourceRef("3.14.6(5)", 182, 144)] },
  { id: "t-2021-no-injection", date: "2021", precision: "year", track: "rescue", impact: "critical", title: "Suntikan RM1.5 bilion 2021 TIDAK diterima", body: "UJSB tidak menerima suntikan yang diperuntukkan dan diluluskan dalam Belanjawan 2021. Keutamaan diberikan kepada perbelanjaan pemulihan ekonomi ekoran Covid-19.", links: ["government-funding"], source: [sourceRef("3.13.48", 166, 128)] },
  { id: "t-2021-alrawda-settle", date: "2021-04", precision: "month", track: "investment", impact: "medium", title: "Perjanjian penyelesaian Al-Rawda SR1,748 juta", body: "Kedua-dua pihak bersetuju terma dan jadual bayaran baharu. Pada 29 Jun 2021 Al-Rawda menawarkan jumlah lebih rendah SR968.0 juta; LTH menolak pada 14 Julai 2021.", links: ["al-rawda"], source: [sourceRef("3.14.6(8)", 186, 148)] },
  { id: "t-2021-ceo-out", date: "2021-05-05", precision: "day", track: "governance", impact: "critical", title: "KPE Datuk Nik Mohd Hasyudeen ditamatkan tanpa sebab", body: "Ditamatkan sebelum tamat tempoh sebenar perkhidmatan (31 Ogos 2021) menggunakan kuasa seksyen 6(5) Akta 535.", links: ["s6-5"], source: [sourceRef("3.2.27", 82, 44)] },
  { id: "t-2021-discipline", date: "2021-09-06", precision: "day", track: "enforcement", impact: "high", title: "Hukuman buang kerja dikurangkan kepada turun pangkat", body: "Jawatankuasa Rayuan Tatatertib mengurangkan hukuman bagi pegawai dalam Kluster 1 (THIP) dan Kluster 3 (hibah 2017).", links: ["disciplinary-actions"], source: [sourceRef("3.15.14 / 3.15.16", 198, 160)] },
  { id: "t-2021-chair-out", date: "2021-10-15", precision: "day", track: "governance", impact: "critical", title: "Pengerusi Tan Sri Md Nor ditamatkan tanpa sebab", body: "Ditamatkan sebelum tamat kontrak dua tahun yang baru disambung mulai 20 Julai 2020.", links: ["s6-5"], source: [sourceRef("3.2.27", 82, 44)] },
  { id: "t-2021-ey-zico", date: "2021", precision: "year", track: "governance", impact: "medium", title: "EY dan ZICO dilantik mengkaji semula model perniagaan", body: "EY mencadangkan LTH dipecahkan kepada tiga entiti; ZICO mencadangkan penambahbaikan Akta 535. Suruhanjaya kemudiannya menolak cadangan pemecahan ini.", links: ["ey-3-entities"], source: [sourceRef("3.17.23", 218, 180)] },
  { id: "t-2021-property-valuation", date: "2021-12-31", precision: "day", track: "rescue", impact: "high", title: "Hartanah UJSB dinilai semula: RM2.25 bilion → RM1.20 bilion", body: "Hartanah yang dipindahkan pada nilai RM2.25 bilion kini bernilai RM1.20 bilion pada nilai pasaran semasa (penilaian jurunilai bebas bertauliah).", links: ["property-transfer-detail"], source: [sourceRef("3.13.34", 160, 122)] },

  /* ---------- 2019–2022: Suruhanjaya ---------- */
  { id: "t-2019-parliament", date: "2019-07-01", precision: "day", track: "inquiry", impact: "high", title: "Parlimen membahaskan Pelan Pemulihan LTH", body: "Beberapa Ahli Parlimen mencadangkan penubuhan Suruhanjaya Siasatan Diraja.", source: [sourceRef("1.1.1", 41, 3)] },
  { id: "t-2020-cabinet-rci", date: "2020-08-14", precision: "day", track: "inquiry", impact: "high", title: "Jemaah Menteri: terdapat keperluan menubuhkan RCI", body: "Susulan Nota Bersama Perdana Menteri dan Menteri Kewangan berdasarkan penemuan BNM, KAN, PwC, EY dan RB.", source: [sourceRef("1.1.2", 41, 3)] },
  { id: "t-2021-cabinet-agree", date: "2021-07-14", precision: "day", track: "inquiry", impact: "high", title: "Jemaah Menteri bersetuju menubuhkan Suruhanjaya", body: "Di bawah Akta Suruhanjaya Siasatan 1950 (Akta 119).", source: [sourceRef("1.1.3", 41, 3)] },
  { id: "t-2021-scope", date: "2021-10-08", precision: "day", track: "inquiry", impact: "high", title: "Objektif dan skop siasatan ditetapkan", body: "Meneliti isu LTH 2014–2020 dengan merujuk penemuan PwC, EY dan RB; menentukan sama ada terdapat penyembunyian maklumat dan kenyataan mengelirukan; mengesyorkan tindakan.", source: [sourceRef("1.3", 42, 4)] },
  { id: "t-2022-appointed", date: "2022-01-20", precision: "day", track: "inquiry", impact: "critical", title: "Enam Pesuruhjaya dilantik", body: "Tempoh kuat kuasa enam bulan sehingga 19 Julai 2022.", source: [sourceRef("1.4.1 / 1.5", 43, 5)] },
  { id: "t-2022-briefings", date: "2022-02-23", precision: "day", dateEnd: "2022-07-07", track: "inquiry", impact: "medium", title: "Taklimat lapan agensi", body: "LTH, EY, Roland Berger, PwC, BNM, JAN, MOF dan UJSB memberi taklimat antara Februari dan Julai 2022.", source: [sourceRef("1.12.2", 46, 8)] },
  { id: "t-2022-hearings", date: "2022-05-09", precision: "day", dateEnd: "2022-06-27", track: "inquiry", impact: "high", title: "16 saksi memberi keterangan secara tertutup", body: "Prosiding di Bilik Mesyuarat, Kompleks Islam Putrajaya dengan kehadiran semua Pesuruhjaya.", source: [sourceRef("1.12.4", 48, 10)] },
  { id: "t-2022-bnm-new", date: "2022-04-18", precision: "day", track: "inquiry", impact: "medium", title: "BNM mengemukakan cadangan model perniagaan baharu", body: "Aktiviti pelaburan LTH dijalankan oleh entiti berasingan yang dikawal selia BNM atau SC. Suruhanjaya menolak cadangan ini.", links: ["bnm-2022"], source: [sourceRef("3.17.17–3.17.19", 216, 178)] },
  { id: "t-2022-hajj-tiers", date: "2022", precision: "year", track: "hajj", impact: "high", title: "Bayaran haji dua lapisan diperkenalkan", body: "RM10,980 (B40) dan RM12,980 (bukan B40) — kenaikan pertama sejak 2009.", links: ["hajj-payment-tiers-2022"], source: [sourceRef("3.16.6", 205, 167)] },
  { id: "t-2022-deposits", date: "2022-05-21", precision: "day", track: "financial", impact: "high", title: "Tanggungan liabiliti pendeposit melebihi RM88 bilion", body: "Ini juga nilai jaminan Kerajaan di bawah seksyen 24 Akta 535 yang terpaksa diaktifkan jika LTH gagal.", links: ["deposit-trajectory", "government-guarantee-exposure"], source: [sourceRef("3.13.50", 171, 133)] },
  { id: "t-2022-signed", date: "2022-07-19", precision: "day", track: "inquiry", impact: "critical", title: "Laporan ditandatangani", body: "Pada hari terakhir tempoh kuat kuasa Pesuruhjaya.", source: [sourceRef("BAB EMPAT", 238, 200)] },
  { id: "t-2022-presented", date: "2022-08-30", precision: "day", track: "inquiry", impact: "critical", title: "Laporan dipersembahkan kepada Yang di-Pertuan Agong", body: "Suruhanjaya berharap Kerajaan menimbang supaya laporan diumumkan kepada awam mengikut bahagian yang bersesuaian.", source: [sourceRef("Muka hadapan / ¶4.6", 5, null)] },

  /* ---------- Titik masa hadapan ---------- */
  { id: "t-2026-siri1", date: "2026", precision: "year", track: "rescue", impact: "critical", future: true, title: "Sukuk Siri 1 matang: RM13.2 bilion", body: "Bayaran pukal (bullet payment) yang perlu dilunaskan sepenuhnya oleh UJSB dengan sokongan Kerajaan.", links: ["ujsb-sukuk"], source: [sourceRef("3.13.62", 171, 133)] },
  { id: "t-2029-siri2", date: "2029", precision: "year", track: "rescue", impact: "critical", future: true, title: "Sukuk Siri 2 matang: RM14.3 bilion", body: "Bayaran pukal kedua. Suruhanjaya khuatir jika Kerajaan tidak dapat memenuhi komitmen, LTH terdedah kepada risiko pembayaran ingkar dan tunggakan keuntungan akan mencecah RM7.65 bilion.", links: ["ujsb-sukuk"], source: [sourceRef("3.13.50 / 3.13.62", 171, 133)] },
  { id: "t-2030-hafis", date: "2030", precision: "year", track: "hajj", impact: "critical", future: true, title: "Unjuran HAFIS mencecah RM742.47 juta setahun", body: "Berdasarkan unjuran LTH: kos haji RM37,729 seorang, bayaran haji kekal RM12,980, HAFIS 65.6% daripada kos haji, 30,000 jemaah setahun.", links: ["hafis-projection"], source: [sourceRef("3.16.8–3.16.9", 205, 167)] },
  { id: "t-2030-quota", date: "2030", precision: "year", track: "hajj", impact: "high", future: true, title: "Kuota haji Malaysia dijangka meningkat kepada 60,000", body: "Mengikut perancangan Kerajaan Arab Saudi (Saudi Vision 2030), daripada lingkungan 30,000 sekarang.", links: ["hajj-quota"], source: [sourceRef("3.16.20", 209, 171)] },
].map((e) => ({ factType: e.future ? "reportProjection" : "fact", ...e }));

/**
 * "Jendela keputusan" — tempoh pendek di mana keputusan besar dibuat
 * dengan masa yang sangat terhad. Berguna sebagai zoom naratif.
 */
export const decisionWindows = [
  {
    id: "window-rescue-2018",
    label: "14 hari untuk menyelamatkan LTH",
    from: "2018-12-07",
    to: "2018-12-27",
    days: 20,
    summary:
      "Jemaah Menteri meluluskan Pelan Pemulihan pada 7 Disember 2018 dengan arahan dilaksanakan sebelum akhir tahun. UJSB ditubuhkan 14 Disember, Perdana Menteri meluluskan pemindahan 19 Disember, dan Perjanjian Pemindahan Aset ditandatangani 27 Disember. Suruhanjaya mencatat LTH mempunyai 'kurang dari dua minggu' untuk memuktamadkan pelan.",
    consequence:
      "Suruhanjaya berpendapat instrumen Sukuk UJSB boleh ditambah baik sekiranya mempunyai ciri jaminan Kerajaan — kekangan masa disebut sebagai sebab ciri itu tiada.",
    source: [sourceRef("3.13.22 / 3.13.59", 156, 118)],
  },
  {
    id: "window-audit-2018",
    label: "12 hari antara perbincangan dan sijil audit",
    from: "2018-07-04",
    to: "2018-07-16",
    days: 12,
    summary:
      "KAN memaklumkan Perdana Menteri pada 4 Julai 2018 bahawa Pendapat Berteguran dicadangkan. Pada 16 Julai 2018, Pendapat Tanpa Teguran dengan 'Emphasis of Matter' dikeluarkan.",
    consequence:
      "Suruhanjaya menyimpulkan KAN mempertimbangkan perkara di luar skop audit (persepsi pihak berkepentingan) dalam membuat keputusan ini.",
    source: [sourceRef("3.11.15", 133, 95)],
  },
  {
    id: "window-rav-2018",
    label: "54 hari: RAV disemak sebelum akaun diaudit",
    from: "2018-05-23",
    to: "2018-07-16",
    days: 54,
    summary:
      "Laporan Semakan RAV EY bagi FY2017 dikeluarkan 23 Mei 2018; Penyata Kewangan Beraudit JAN baru dimuktamadkan 16 Julai 2018.",
    consequence:
      "Suruhanjaya mendapati dakwaan bahawa Proforma berasaskan penyata kewangan beraudit adalah TIDAK BENAR.",
    source: [sourceRef("3.9.19", 118, 80)],
  },
  {
    id: "window-hibah-2018",
    label: "Tiga hari mesyuarat khas Lembaga",
    from: "2018-02-06",
    to: "2018-02-09",
    days: 3,
    summary:
      "Dua Mesyuarat Khas Lembaga Pengarah pada 6 dan 9 Februari 2018 di mana dua kertas kerja mengenai hibah 2017 dibentangkan. Pada 14 Februari 2018, laporan kewangan dibentangkan semula berserta pindaan polisi rosot nilai.",
    consequence:
      "Menjadi asas laporan polis Dang Wangi/1484/2019 yang mendakwa wujud salah nyataan bagi membolehkan hibah tinggi diisytiharkan.",
    source: [sourceRef("3.15.8 / 3.11.5", 196, 158)],
  },
].map((w) => ({ factType: "derived", derivationNote: "Tempoh dikira daripada tarikh yang dinyatakan laporan.", ...w }));
