const D=window.RCI_DATA;
const $=(q,el=document)=>el.querySelector(q), $$=(q,el=document)=>[...el.querySelectorAll(q)];
const fmtRM=(n,d=2)=>Math.abs(n)>=1000?`${n<0?'−':''}RM${(Math.abs(n)/1000).toFixed(d)}b`:`${n<0?'−':''}RM${Math.abs(n).toFixed(n%1?1:0)}j`;
const money=n=>'RM'+Math.round(n).toLocaleString('ms-MY');
const sourceUrl=p=>`${D.source}#pdf-page-${p}`;

function openModal(html){$('#modalContent').innerHTML=html;$('#modal').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('.modal-close').focus(),0)}
function closeModal(){$('#modal').hidden=true;document.body.style.overflow='';}
$$('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$$('[data-open-source]').forEach(b=>b.addEventListener('click',()=>window.open(D.source,'_blank','noopener')));
$$('[data-open-method]').forEach(b=>b.addEventListener('click',()=>openModal(`<p class="eyebrow">Tentang data</p><h2 id="modalTitle">Bagaimana dashboard ini dibina</h2><p>Semua angka fakta diambil terus daripada teks OCR laporan RCI. Data terbitan—contohnya premium sebagai peratus nilai pasaran—dikira daripada angka laporan. Simulasi HAFIS pula dilabel jelas dan tidak dianggap ramalan RCI.</p><ul><li><b>Fakta laporan:</b> angka atau kenyataan yang dinyatakan dalam laporan.</li><li><b>Data terbitan:</b> hasil tolak, bahagi atau perbandingan fakta laporan.</li><li><b>Simulasi:</b> nilai yang berubah mengikut input pengguna.</li></ul><p>Kesalahan OCR yang jelas seperti “1.259” ditafsir sebagai 1.25% hanya apabila jadual lain dalam laporan mengesahkannya.</p><a class="source-btn source-link" target="_blank" rel="noopener" href="${D.source}">Baca laporan penuh ↗</a>`)));
$$('[data-source]').forEach(b=>b.addEventListener('click',()=>window.open(sourceUrl(b.dataset.source),'_blank','noopener')));

const menu=$('#menuBtn'),drawer=$('#mobileDrawer');menu.addEventListener('click',()=>{const o=drawer.classList.toggle('open');menu.setAttribute('aria-expanded',o);drawer.setAttribute('aria-hidden',!o)});$$('a',drawer).forEach(a=>a.addEventListener('click',()=>{drawer.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

function renderCausal(active='mandat'){
  $('#causalMap').innerHTML=D.causal.map(x=>`<button class="causal-node ${x.id===active?'active':''}" data-id="${x.id}" role="listitem"><span>${x.n} · ${x.type==='fact'?'KONTEKS':x.type==='finding'?'PENEMUAN':'KESAN'}</span><h3>${x.title}</h3><p>${x.short}</p></button>`).join('');
  const x=D.causal.find(x=>x.id===active),idx=D.causal.indexOf(x),next=D.causal[idx+1];
  $('#causalDetail').innerHTML=`<span class="type">${x.n} · ${x.type==='fact'?'Konteks laporan':x.type==='finding'?'Penemuan RCI':'Kesan yang dinyatakan'}</span><h3>${x.title}</h3><p>${x.detail}</p><button class="evidence-chip inverse" data-page="${x.page}">Buka bukti halaman ${x.page} ↗</button>${next?`<div class="next"><b>Seterusnya →</b><br>${next.title}</div>`:''}`;
  $$('[data-id]',$('#causalMap')).forEach(b=>b.onclick=()=>renderCausal(b.dataset.id));$('[data-page]',$('#causalDetail')).onclick=e=>window.open(sourceUrl(e.currentTarget.dataset.page),'_blank','noopener');
}renderCausal();

let gapMode='post';function renderGap(){
  const vals=D.gap.map(x=>x[gapMode]),max=Math.max(...vals.map(Math.abs));
  $('#gapChart').innerHTML=D.gap.map(x=>{const v=x[gapMode],h=Math.abs(v)/max*44;return `<div class="bar-group"><div class="bar-value" style="${v>=0?`bottom:${50+h}%`:`top:${52+h}%`}">${fmtRM(v)}</div><i class="bar ${v>=0?'positive':'negative'}" style="height:${h}%;"></i>${$('#showDistribution').checked?`<i class="dist-mark" title="Hibah ${fmtRM(x.distribution)}" style="top:${Math.max(4,50-(x.distribution/max*44))}%"></i>`:''}<span class="bar-year">${x.year}</span></div>`}).join('');
  $('#gapKicker').textContent=`Kekurangan / lebihan ${gapMode==='post'?'selepas':'sebelum'} hibah`;$('#gapHeadline').textContent=`${fmtRM(D.gap.at(-1)[gapMode])} pada 2017`;
}renderGap();$$('#gapMode button').forEach(b=>b.onclick=()=>{$$('#gapMode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');gapMode=b.dataset.mode;renderGap()});$('#showDistribution').onchange=renderGap;

function svgLine(points,color,w,h,max){return `<polyline fill="none" stroke="${color}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${points.map((p,i)=>`${i*w/(points.length-1)},${h-(p/max*h)}`).join(' ')}"/>`}
function renderHibah(active=2014){const w=760,h=245,max=9,pad=22,aw=w-pad*2,ah=h-pad*2,total=D.hibah.map(x=>x.annual+x.hajj),annual=D.hibah.map(x=>x.annual);
  const coords=total.map((v,i)=>({x:pad+i*aw/(total.length-1),y:pad+ah-v/max*ah}));
  $('#hibahChart').innerHTML=`<svg viewBox="0 0 ${w} ${h+25}" role="img" aria-label="Kadar hibah 2014 hingga 2021">${[0,3,6,9].map(v=>`<line x1="${pad}" y1="${pad+ah-v/max*ah}" x2="${w-pad}" y2="${pad+ah-v/max*ah}" stroke="#dfe3de"/><text x="0" y="${pad+ah-v/max*ah+4}" font-size="9" fill="#7b8983">${v}%</text>`).join('')}${svgLine(total,'#0e5c43',aw,ah,max).replaceAll(/([0-9.]+),([0-9.]+)/g,(m,x,y)=>`${+x+pad},${+y+pad}`)}${svgLine(annual,'#d8a93d',aw,ah,max).replaceAll(/([0-9.]+),([0-9.]+)/g,(m,x,y)=>`${+x+pad},${+y+pad}`)}${coords.map((p,i)=>`<circle class="point" data-year="${D.hibah[i].year}" cx="${p.x}" cy="${p.y}" r="${D.hibah[i].year===active?7:5}" fill="${D.hibah[i].year===active?'#d75b4b':'#fff'}" stroke="#0e5c43" stroke-width="3" tabindex="0"/><text x="${p.x}" y="${h+15}" text-anchor="middle" font-size="9" fill="#66736e">${D.hibah[i].year}</text>`).join('')}</svg>`;
  const x=D.hibah.find(x=>x.year===active);$('#hibahHeadline').textContent=`${x.year}: ${(x.annual+x.hajj).toFixed(2)}%`;$('#hibahDetail').innerHTML=`<span class="chart-kicker">Tahun ${x.year}</span><div class="big-rate">${(x.annual+x.hajj).toFixed(2)}%</div><div class="split"><div><span>Hibah tahunan</span><b>${x.annual.toFixed(2)}%</b></div><div><span>Hibah haji</span><b>${x.hajj.toFixed(2)}%</b></div></div>${x.totalRm?`<p><b>${fmtRM(x.totalRm)}</b> jumlah diagih</p>`:''}<p>${x.note}</p>`;
  $$('.point',$('#hibahChart')).forEach(p=>{p.onclick=()=>renderHibah(+p.dataset.year);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')renderHibah(+p.dataset.year)}})
}renderHibah();

function renderHafisArea(){const all=[...D.hafisActual,...D.hafisProjection],w=900,h=250,p=25,max=40000,pts=(key)=>all.map((x,i)=>`${p+i*(w-p*2)/(all.length-1)},${h-p-x[key]/max*(h-p*2)}`).join(' ');$('#hafisChart').innerHTML=`<svg viewBox="0 0 ${w} ${h+25}" role="img"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0e5c43" stop-opacity=".28"/><stop offset="1" stop-color="#0e5c43" stop-opacity="0"/></linearGradient></defs><polygon points="${p},${h-p} ${pts('cost')} ${w-p},${h-p}" fill="url(#area)"/><polyline points="${pts('cost')}" fill="none" stroke="#0e5c43" stroke-width="3"/><polyline points="${pts('payment')}" fill="none" stroke="#d8a93d" stroke-width="3" stroke-dasharray="6 5"/>${all.map((x,i)=>i%2===0?`<text x="${p+i*(w-p*2)/(all.length-1)}" y="${h+12}" text-anchor="middle" font-size="9" fill="#66736e">${x.year}</text>`:'').join('')}<text x="${w-80}" y="38" font-size="10" fill="#0e5c43">Kos sebenar</text><text x="${w-85}" y="${h-80}" font-size="10" fill="#a17412">Bayaran jemaah</text></svg>`}renderHafisArea();
function updateSim(){const year=+$('#yearSlider').value,item=D.hafisProjection.find(x=>x.year===year),pay=Math.min(+$('#paymentSlider').value,item.cost),pilgrims=+$('#pilgrimSlider').value,gap=Math.max(0,item.cost-pay),pct=gap/item.cost*100,total=gap*pilgrims/1e6;$('#yearOutput').textContent=year;$('#paymentOutput').textContent=money(pay);$('#pilgrimOutput').textContent=pilgrims.toLocaleString('ms-MY');$('#costResult').textContent=money(item.cost);$('#perPersonResult').textContent=money(gap);$('#totalResult').textContent=`RM${total.toFixed(2)} juta`;$('#hafisPct').textContent=pct.toFixed(1)+'%';$('#hafisDonut').style.setProperty('--pct',pct);const diff=total-item.total;$('#deltaResult').textContent=Math.abs(diff)<.1?`Sama seperti unjuran laporan ${year}`:`${diff>0?'+':'−'}RM${Math.abs(diff).toFixed(1)}j berbanding unjuran laporan ${year}`;$('#fullCostBtn').dataset.pay=item.cost;}
['yearSlider','paymentSlider','pilgrimSlider'].forEach(id=>$('#'+id).oninput=updateSim);$$('[data-pay]').forEach(b=>b.onclick=()=>{$$('#paymentSlider').value=+b.dataset.pay;$$('[data-pay]').forEach(x=>x.classList.remove('active'));b.classList.add('active');updateSim()});updateSim();

$('#assetBreakdown').innerHTML=D.assetTypes.map(x=>`<div class="asset-row"><span>${x.name}</span><div class="asset-track"><i style="width:${x.transfer/16851*100}%;background:${x.color}"></i></div><b>${fmtRM(x.transfer)}</b></div>`).join('');$('#assetToggle').onclick=()=>{const o=$('#assetBreakdown').classList.toggle('open');$('#assetToggle').textContent=o?'Sembunyi pecahan':'Lihat ikut jenis'};

let invFilter='all',invSearch='',activeInv='fgv';function renderInvestments(){let rows=D.investments.filter(x=>(invFilter==='all'||x.place===invFilter||x.status===invFilter)&&(x.name+' '+x.issue+' '+x.category).toLowerCase().includes(invSearch));$('#investmentList').innerHTML=rows.map(x=>`<button class="investment-item ${x.id===activeInv?'active':''}" data-id="${x.id}"><span class="meta">${x.country} · ${x.category}</span><b>${x.name}</b><strong>${x.headline}</strong><span class="severity">${[1,2,3,4,5].map(i=>`<i class="${i<=x.severity?'on':''}"></i>`).join('')}</span></button>`).join('')||'<p>Tiada kes sepadan.</p>';if(!rows.find(x=>x.id===activeInv)&&rows[0])activeInv=rows[0].id;const x=D.investments.find(x=>x.id===activeInv);if(x)$('#investmentDetail').innerHTML=`<span class="detail-meta">${x.country} · ${x.category} · ${x.status}</span><h3>${x.name}</h3><div class="headline">${x.headline}</div><div class="metric-list">${x.metrics.map(m=>`<div><span>${m[0]}</span><b>${m[1]}</b></div>`).join('')}</div><div class="detail-block"><span>Apa masalahnya</span><p>${x.issue}</p></div><div class="detail-block"><span>Tindakan ketika laporan</span><p>${x.action}</p></div><button class="source-btn dark" data-inv-source="${x.page}">Bukti halaman ${x.page} ↗</button>`;$$('.investment-item').forEach(b=>b.onclick=()=>{activeInv=b.dataset.id;renderInvestments()});const sb=$('[data-inv-source]');if(sb)sb.onclick=()=>window.open(sourceUrl(sb.dataset.invSource),'_blank','noopener')}
renderInvestments();$$('#investmentFilters button').forEach(b=>b.onclick=()=>{$$('#investmentFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');invFilter=b.dataset.filter;renderInvestments()});$('#investmentSearch').oninput=e=>{invSearch=e.target.value.toLowerCase();renderInvestments()};

$('#bonusChart').innerHTML=D.bonus.map(x=>`<div class="bonus-bar"><b>${x.value}</b><i style="height:${x.value/74*80}%"></i><span>${String(x.year).slice(2)}</span></div>`).join('');function renderRecipients(y){const max=Math.max(...D.recipients[y].map(x=>x[1]));$('#recipientList').innerHTML=D.recipients[y].map(x=>`<div class="recipient"><span>${x[0]}</span><b>RM${x[1].toLocaleString('ms-MY')}</b></div>`).join('')}renderRecipients(2017);$$('#recipientYear button').forEach(b=>b.onclick=()=>{$$('#recipientYear button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRecipients(b.dataset.year)});

$('#recommendations').innerHTML=D.recommendations.map(x=>`<article class="rec-card"><span class="rec-area">${x.area}</span><h3>${x.title}</h3><p>${x.plain}</p><button class="evidence-chip" data-rec="${x.page}">Bukti hlm. ${x.page} ↗</button></article>`).join('');$$('[data-rec]').forEach(b=>b.onclick=()=>window.open(sourceUrl(b.dataset.rec),'_blank','noopener'));
let timelineType='all';function renderTimeline(){const rows=D.timeline.filter(x=>timelineType==='all'||x.type===timelineType);$('#timeline').innerHTML=rows.map(x=>`<article class="timeline-item" data-type="${x.type}"><time>${x.date} · ${x.type}</time><h3>${x.title}</h3><p>${x.text}</p></article>`).join('')}renderTimeline();$$('#timelineFilter button').forEach(b=>b.onclick=()=>{$$('#timelineFilter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');timelineType=b.dataset.type;renderTimeline()});
